version: '3'

networks:
  useman-network:
    driver: bridge
    ipam:
      driver: default

services:
    useman-nginx:
        container_name: useman-nginx
        image: nginx
        ports:
            - '8080:80'
        links:
            - useman-php
        volumes:
            - ../src:/var/www
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs/access.log:/var/log/nginx/access.log
            - ./nginx/logs/error.log:/var/log/nginx/error.log        
        networks:
            - useman-network

    useman-php:
        build:
            context: .
            dockerfile: ./php/php.Dockerfile
        container_name: useman-php
        image: useman-php
        ports:
            - '9000:9000'
        volumes:
            - ../src:/var/www
            - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - useman-network

    useman-mysql:
        container_name: useman-mysql
        image: mysql:8.0
        ports:
            - '3306:3306'
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=useman
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
        networks:
            - useman-network